// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abfadmttrsujauqsfjgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZmFkbXR0cnN1amF1cXNmamd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjYxNDYsImV4cCI6MjA2OTY0MjE0Nn0.GF8jNkwjmC1ZzcKDGnyxNzI3c7c2B4kljoJB2p1y8Z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});